### ISSUE TITLE
Forge tests fails with "No target contract" message

### ISSUE THREAD

**Issue by grandizzy** [gakonst/foundry#1184]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a279d2e 2022-04-04T00:03:20.128570951+00:00)

### What command(s) is the bug in?

forge test --optimize --optimize-runs 1000000 -v

### Operating System

Linux

### Describe the bug

Both CI pipeline (using https://github.com/onbjerg/foundry-toolchain) and local forge tests started to fail since updating to latest nightly build, see output below. Tests are located in `src/_test` directory. Also if building foundry without https://github.com/gakonst/foundry/commit/5827745d5d938b9c757a6ee943290481cf7426ee works just fine

```
The application panicked (crashed).
Message:  No target contract
Location: utils/src/lib.rs:217

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>
```

**Comment by grandizzy** [comment]
it works fine if building without https://github.com/gakonst/foundry/commit/5827745d5d938b9c757a6ee943290481cf7426ee

**Comment by onbjerg** [comment]
My findings too, on Telegram (with a reproducible example):

>it was broken in https://github.com/gakonst/foundry/pull/978
>
>cc @mattsse: running forge test before #978 was merged works fine, but as soon as #978 is merged then running forge test in https://github.com/FrenchyPeanut/NFT-with-Foundry/tree/master/packages/hardhat panics:
>
>The application panicked (crashed).
>Message:  No target contract
>Location: utils/src/lib.rs:217
>
>Backtrace omitted.
>Run with RUST_BACKTRACE=1 environment variable to display it.
>Run with RUST_BACKTRACE=full to include source snippets.
>fish: Job 1, 'forge test' terminated by signal SIGABRT (Abort)

**Comment by grandizzy** [comment]
so debugging some more it looks like the source contracts are not built together with `forge test`, doing `forge build && forge test` worked for me ...

**Comment by onbjerg** [comment]
Are you using libraries, or just normal contracts?

**Comment by mattsse** [comment]
should be resolved since we reverted sparse mode #1189 
and root issue fixed here https://github.com/gakonst/ethers-rs/pull/1107

**Comment by danielattilasimon** [comment]
I can still reproduce the issue with the latest version (`forge 0.2.0 (bab38d6 2022-05-06T00:07:49.001076+00:00)` at the time I'm writing this) but _only_ if I try to debug a test case.

I made a minimal example project that demonstrates the issue:
https://github.com/danielattilasimon/foundry-bug

I just did `forge init` and added a dummy library, which I'm importing from _only from within tests_ (though I don't know if that matters or not).

`forge test` works fine:
```
❯ forge test
[⠒] Compiling...
No files changed, compilation skipped

Running 1 test for test/Contract.t.sol:ContractTest
[PASS] testExample() (gas: 3262)
Test result: ok. 1 passed; 0 failed; finished in 6.25ms
```

If I try to debug a test case, it fails:
```
❯ forge test --debug testExample
[⠔] Compiling...
No files changed, compilation skipped
[⠢] Compiling...
[⠰] Compiling 7 files with 0.8.13
[⠒] Solc 0.8.13 finished in 2.16s
Compiler run successful
The application panicked (crashed).
Message:  No target contract
Location: utils/src/lib.rs:218

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
fish: Job 1, 'forge test --debug testExample' terminated by signal SIGABRT (Abort)
```
