### ISSUE TITLE
Initial address incompatibility

### ISSUE THREAD

**Issue by exp-table** [gakonst/foundry#249]
I noticed that the sequence of addresses assigned to contracts deployed in any test is not identical to the one produced by dapptools. 

In my case, it breaks a particular case where I generate a merkle tree with the addresses of custom `User` contracts. Their respectives proofs are hardcoded. Thus, the proofs ingested by some functions are therefore invalid.

@brockelmore and @gakonst suggested that the reasons are probably the initial address and the nonce(s).

**Comment by mds1** [comment]
If I'm understanding this issue correctly, then @gakonst we saw this a while back when you tried to verify foundry against the Drai repo, since there's a hardcoded address validation test [here](https://github.com/mds1/drai/blob/f31ce4fb15bbb06c94eefea2a3a43384c75b95cf/src/Drai.t.sol#L73-L76). That test passes on dapptools but failed against foundry, so it might be another useful reference to test against

**Comment by gakonst** [comment]
Yep, same issue @mds1

**Comment by brockelmore** [comment]
does anyone know the dapptools initial address? easiest to just match that as default to maintain max compatibility

**Comment by transmissions11** [comment]
It's in the hevm README I'll dig it up in a sec

**Comment by brockelmore** [comment]
looks like its `0x00a329c0648769a73afac7f9381e08fb43dbea72`

**Comment by byterose** [comment]
@exp-table Interested to see how you use dapp.tools to test a merkle tree. Could you share the repo?

**Comment by transmissions11** [comment]
> 0x00a329c0648769a73afac7f9381e08fb43dbea72

yup https://github.com/dapphub/dapptools/tree/master/src/hevm#environment-variables

**Comment by brockelmore** [comment]
ah interesting issue here: i think the real issue is the address of the *test* contract, not the sender. See [here](https://github.com/dapphub/dapptools/tree/master/src/hevm#environment-variables). I tried on @exp-table's repo setting the sender variable to the above, and it still failed. 

The hard part is that we support *multiple* test contracts. Which is the right thing to do for parallelizing tests, but means that we can't easily support without some compromises. One option is to not pre-deploy per test, and just in `run_test` do a `set_code` into the specified address, which is what i imagine hevm does under the hood

**Comment by brockelmore** [comment]
Work around for anyone stumbling upon this and needs a short term fix:
```solidity
contract Test {
    function setUp() public {
        vm.startPrank(<expectedAddress>);
        DeterministicContractAddress contract = new DeterministicContractAddress();
    }
}
```

use the `startPrank` cheatcode in your setup function prior to deploying any subsequent contracts. This may be the preferred long term solution

**Comment by fmhall** [comment]
Interestingly, setting `DAPP_TEST_CALLER` and `DAPP_TEST_ADDRESS` sets the addresses, but to different ones than I specified

**Comment by onbjerg** [comment]
> Interestingly, setting `DAPP_TEST_CALLER` and `DAPP_TEST_ADDRESS` sets the addresses, but to different ones than I specified

`DAPP_TEST_CALLER` is (mistakenly) not used by Forge, it uses `DAPP_TEST_ADDRESS` to set the sender (see #253). If you set `DAPP_TEST_ADDRESS` to `0x00a329c0648769a73afac7f9381e08fb43dbea72` then the first test contract address will match dapptools

**Comment by onbjerg** [comment]
Hmm, this seems to not have been fixed anyway, which is strange. The sender is correct, but now the test contract address is always incorrect (not even the first one matches)

**Comment by gakonst** [comment]
You are right, it is still happening. Unsure / haven't debugged.

**Comment by onbjerg** [comment]
Figured out the issue, it seems that the dapptools address is from nonce 1 of the `0x00a329c0648769A73afAc7F9381E08FB43dBEA72` account whereas we deploy the contract at nonce 0.

PR #446 fixes it
