### ISSUE TITLE
Compiling a solidity library file with enum fails

### ISSUE THREAD

**Issue by smsunarto** [gakonst/foundry#349]
**What happened?**

~Compilation failed (error below) when compiling a solidity file with imported enum as function parameters (enum declared in a separate library file)~

EDIT: Compilation failed (error below) when compiling a solidity **library** file with enum as function parameter or return values.

```
forge build --root ~/git/project/eth --remappings @opengsn/=lib/gsn/packages/ @openzeppelin/=lib/openzeppelin-contracts/ --force
compiling...
Error: 
   0: InvalidName("LibTypes.CreatureSpecies") at line 1 column 3857567

Location:
   cli/src/cmd/build.rs:96

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 4 frames hidden ⋮                               
   5: forge::main::hd27355d3833fe780
      at <unknown source file>:<unknown line>
   6: std::sys_common::backtrace::__rust_begin_short_backtrace::hcb887eac5a464574
      at <unknown source file>:<unknown line>
   7: _main<unknown>
      at <unknown source file>:<unknown line>
```

## Isolated Failing Code

**Enum in function param**
```
pragma solidity ^0.7.6;

library LibTest {
    enum TestEnum {
        A,
        B,
        C
    }

    function foobar(TestEnum test) public view {}
}
```

**Enum in function return**
```
pragma solidity ^0.7.6;

library LibTest {
    enum TestEnum {
        A,
        B,
        C
    }

    function foobar() public view returns (TestEnum test) {}
}
```

NOTE: Both of these works fine if it is a `contract` instead of `library`

**Possible explanation**
Might be caused by ethabi? There's a "similar" issue although for a different case: https://github.com/rust-ethereum/ethabi/issues/75

**Comment by gakonst** [comment]
This is odd, can you try sharing a code example that reproduces this issue?

**Comment by smsunarto** [comment]
> This is odd, can you try sharing a code example that reproduces this issue?

Just updated the original post with the isolated code + additional comments

**Comment by gakonst** [comment]
Thanks! Also wonder if it's related to the library function being `public` instead of `internal`..In any case, cc @mattsse

**Comment by smsunarto** [comment]
Yes, it only fails on public library functions.

For example, this compiles fine.
```
pragma solidity ^0.7.6;

library LibTest {
    enum TestEnum {
        A,
        B,
        C
    }

    function foobar() internal view returns (TestEnum test) {}
}

contract Main {
    function foo() public view {
        LibTest.foobar();
    }
}
```

**Comment by gakonst** [comment]
Thanks @smsunarto this ended up being an ethabi issue: https://github.com/rust-ethereum/ethabi/issues/254.

**Comment by gakonst** [comment]
@smsunarto This should be fixed in latest master https://github.com/gakonst/foundry/commit/f8f595e5c398de8856a8bb22f35931820919efaf

**Comment by smsunarto** [comment]
@gakonst Just got the chance to test this again, seems like error still occurs. The location of the error changes though.

```
forge clean && forge build --optimize --optimize-runs 1000000 --root .
compiling...
Error: 
   0: InvalidName("LibTypes.CreatureSpecies") at line 1 column 2427977

Location:
   cli/src/cmd/mod.rs:47

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 4 frames hidden ⋮                               
   5: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual::h3437762df847f385
      at <unknown source file>:<unknown line>
   6: forge::cmd::compile::h1dd3d4345dd934d5
      at <unknown source file>:<unknown line>
   7: forge::main::hd697c8449f856e90
      at <unknown source file>:<unknown line>
   8: std::sys_common::backtrace::__rust_begin_short_backtrace::ha973407a9d66719c
      at <unknown source file>:<unknown line>
   9: _main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
make: *** [build] Error 1
```
